spring:
  # 使用druid数据源
  datasource:
    name: ctable
    url: jdbc:mysql://localhost:3306/ctable?characterEncoding=utf8&useSSL=false&autoReconnect=true&serverTimezone=GMT
    username: root
    password: root
server:
    port: 8088